# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.find_or_create_by_name([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

puts "Creating Status records..."
Status.find_or_create_by_name(name: "New")
Status.find_or_create_by_name(name: "Approved")
Status.find_or_create_by_name(name: "Pending")
Status.find_or_create_by_name(name: "Denied")
Status.find_or_create_by_name(name: "Cancelled")
Status.find_or_create_by_name(name: "Updated")

puts "Creating Campus records..."



User.find_or_create_by_firstname(firstname: "Jim",      lastname: "Jastatt",   address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "jjastatt", password: "abcde.find_or_create_by_name", active: TRUE)
User.find_or_create_by_firstname(firstname: "Kayla",    lastname: "Ledger",    address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "kledger", password: "abcde", active: TRUE)
User.find_or_create_by_firstname(firstname: "Mamadou",  lastname: "Ndiaye Jr", address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "mndiaye", password: "abcde", active: TRUE)
User.find_or_create_by_firstname(firstname: "Mike",     lastname: "Spencer",   address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "mspencer", password: "abcde", active: TRUE)
User.find_or_create_by_firstname(firstname: "Michelle", lastname: "Peterson",  address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "mpeterson", password: "abcde", active: TRUE)
User.find_or_create_by_firstname(firstname: "Rich",     lastname: "Fowler",    address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "rfowler", password: "abcde", active: TRUE)
User.find_or_create_by_firstname(firstname: "Kevin",    lastname: "Malloy",    address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "kmalloy", password: "abcde", active: TRUE)
User.find_or_create_by_firstname(firstname: "Brad",     lastname: "Savage",    address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "bsavage", password: "abcde", active: TRUE)
User.find_or_create_by_firstname(firstname: "Terry",    lastname: "Polomsky",  address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "tpolomsky", password: "abcde", active: TRUE)
User.find_or_create_by_firstname(firstname: "Kyle",     lastname: "Spreitzer", address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "kspreitzer", password: "abcde", active: TRUE)
User.find_or_create_by_firstname(firstname: "Wendy",    lastname: "Wotowiec",  address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "wwotoweic", password: "abcde", active: TRUE)
User.find_or_create_by_firstname(firstname: "Todd",     lastname: "Samms",     address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "mtsamms", password: "abcde", active: TRUE)
User.find_or_create_by_firstname(firstname: "Danny",    lastname: "Snipes",    address: "123 Tower Way", city: "Kent", state: "OH", zip: "44242", userid: "dsnipes", password: "abcde", active: TRUE)


Building.find_or_create_by_name(name: "Main Hall", campus_id: campuses.first, user_id: 1)
Building.find_or_create_by_name(name: "Health and Science Building", campus_id: campuses.first, user_id: 1)
Building.find_or_create_by_name(name: "Technology Building", campus_id: campuses.first, user_id: 1)
Building.find_or_create_by_name(name: "Library", campus_id: campuses.first, user_id: 2)
Building.find_or_create_by_name(name: "Main Building", campus_id: campuses.second)
Building.find_or_create_by_name(name: "Mary Patterson Building", campus_id: campuses.second)
Building.find_or_create_by_name(name: "Memorial Auditorium", campus_id: campuses.second)
Building.find_or_create_by_name(name: "Geauga Hall", campus_id: campuses.third)
Building.find_or_create_by_name(name: "Twinsburg", campus_id: campuses.third)
Building.find_or_create_by_name(name: "Administrative Services Building", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Allyn Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Art Annex", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Art Building", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Beall Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Beck Family Gardens", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Bowman Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Business Administration Building", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Cartwright Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Centennial Court A", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Centennial Court B", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Centennial Research Park", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Ceremics Laboratory", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Child Development Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Clark Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Cunningham Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "DeWeese Health Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Dix Stadium", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Dunbar Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Eastway Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Engleman Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Field House", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Fletcher Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Foundation and Development", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Franklin Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Gym Annex", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Harbourt Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Heer Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Henderson Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Hillel", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Ice Arena", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Johnson Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Kent Center for the Performing Arts", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Kent Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Kent Pavers", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Kent Sate Hotel and Conference Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Kent Student Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Kiva", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Koonce Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Korb Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Lake Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Leebrick Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Leppo Garden", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Library", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Lincoln Building", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Liquid Crystals Materials Science Building", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Lowry Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Manchester Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Mathematics and Computer Science Building", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "McDowell Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "McGilvrey Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Memorial Athletic and Convocation Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Merrill Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Moulton Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Nixson Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Observatory", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Olson Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Prentice Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Ritchie Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Rockwell Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Satterfield Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Schoonover Stadium", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Schwartz Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Science Research Building", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Smith Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Stewart Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Stockdale Building", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Stopher Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Student Recreation and Wellness Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Taylor Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Terrace Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Tri-Towers Complex", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Twin Towers Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Van Campen Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Van Deusen Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Verder Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "White Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Williams Hall", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Williamson Alumni Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "WKSU Broadcast Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Womens Center", campus_id: campuses.fourth)
Building.find_or_create_by_name(name: "Wright Hall", campus_id: campuses.fourth)



